# Generated by Django 5.1.3 on 2024-11-25 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.district')),
            ],
        ),
        migrations.CreateModel(
            name='ReservoirData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basin', models.CharField(max_length=255)),
                ('gross_capacity', models.FloatField()),
                ('current_level', models.FloatField()),
                ('current_storage', models.FloatField()),
                ('flood_cushion', models.FloatField()),
                ('inflow', models.FloatField()),
                ('outflow', models.FloatField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.district')),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservoir.reservoir')),
            ],
            options={
                'verbose_name': 'Reservoir Data',
                'verbose_name_plural': 'Reservoir Data',
            },
        ),
    ]
