# Generated by Django 5.1.3 on 2024-11-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('agency_name', models.CharField(max_length=255)),
                ('frl', models.FloatField()),
                ('live_cap_frl', models.FloatField()),
                ('level', models.FloatField()),
                ('current_live_storage', models.FloatField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
            ],
        ),
    ]
