# Generated by Django 5.1.3 on 2024-11-19 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
        ('reservoir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservoir',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.state'),
        ),
    ]
