# Generated by Django 5.1.3 on 2024-11-26 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_alter_usage_reservoir'),
        ('reservoir', '0003_remove_reservoir_district_reservoir_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservoir',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forecast.district'),
        ),
    ]
