# Generated by Django 5.1.3 on 2024-11-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_alter_usage_reservoir'),
        ('reservoir', '0004_reservoir_district'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservoirdata',
            index=models.Index(fields=['reservoir', 'year'], name='reservoir_r_reservo_f400bc_idx'),
        ),
    ]
