# Generated by Django 5.0.2 on 2024-12-08 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservoir', '0006_reservoirprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservoirScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('mean_storage', models.FloatField()),
                ('flood_cushion', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('evaporation', models.FloatField()),
                ('population', models.BigIntegerField()),
                ('age', models.IntegerField()),
                ('siltation', models.FloatField()),
                ('capacity', models.FloatField()),
                ('score', models.FloatField()),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservoir.reservoir')),
            ],
        ),
    ]
