# Generated by Django 5.1.3 on 2024-12-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservoir', '0008_reservoirprediction_evaporation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservoirprediction',
            name='month',
            field=models.IntegerField(null=True),
        ),
    ]
