# Generated by Django 5.0.2 on 2024-12-29 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('forecast', '0013_delete_landuse'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(null=True)),
                ('risk_type', models.CharField(max_length=25)),
                ('description', models.TextField(null=True)),
                ('causes', models.TextField(null=True)),
                ('mitigation', models.TextField(null=True)),
                ('risk_score', models.IntegerField()),
                ('factors', models.TextField(null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.district')),
            ],
            options={
                'indexes': [models.Index(fields=['district', 'year'], name='risk_riskda_distric_963944_idx')],
            },
        ),
    ]
