# Generated by Django 5.0.2 on 2024-12-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskdata',
            name='risk_type',
            field=models.TextField(null=True),
        ),
    ]
