# Generated by Django 5.1.1 on 2024-11-14 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_population', models.FloatField()),
                ('urban_population', models.FloatField()),
                ('rural_population', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LandUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('forest_use', models.FloatField()),
                ('barren_use', models.FloatField()),
                ('fallow_use', models.FloatField()),
                ('cropped_use', models.FloatField()),
                ('other_use', models.FloatField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.state')),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('domestic_use', models.FloatField()),
                ('industrial_use', models.FloatField()),
                ('irrigation_use', models.FloatField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.state')),
            ],
        ),
    ]
