# Generated by Django 5.1.3 on 2024-11-25 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LandUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('forest_use', models.FloatField()),
                ('barren_use', models.FloatField()),
                ('fallow_use', models.FloatField()),
                ('cropped_use', models.FloatField()),
                ('other_use', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('rainfall', models.FloatField()),
                ('inflow_states', models.FloatField()),
                ('ground_water', models.FloatField()),
                ('soil_moisture', models.FloatField()),
                ('reservoir', models.FloatField()),
                ('major', models.FloatField()),
                ('medium', models.FloatField()),
                ('mi_tanks', models.FloatField()),
                ('evapo_trans', models.FloatField()),
                ('outflow', models.FloatField()),
                ('river', models.FloatField()),
                ('micro_basin', models.FloatField()),
                ('consumption', models.FloatField()),
                ('irrigation', models.FloatField()),
                ('industry', models.FloatField()),
                ('domestic', models.FloatField()),
                ('subsurface_outflow', models.FloatField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.district')),
            ],
        ),
    ]
