# Generated by Django 5.1.3 on 2024-11-21 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('district', models.CharField(max_length=200)),
                ('level', models.FloatField()),
                ('volume', models.FloatField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.state')),
            ],
        ),
    ]
