# Generated by Django 5.0.2 on 2024-11-27 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_alter_usage_reservoir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evapo_transpiration', models.FloatField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_evaporation', models.FloatField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.district')),
            ],
        ),
    ]
