# Generated by Django 5.0.2 on 2024-11-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_evaporation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='reservoir',
            field=models.FloatField(),
        ),
    ]
