# Generated by Django 5.1.3 on 2024-11-29 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_rainfall'),
    ]

    operations = [
        migrations.CreateModel(
            name='LucPredictionDist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('built_up', models.FloatField()),
                ('agriculuture', models.FloatField()),
                ('forest', models.FloatField()),
                ('wasteland', models.FloatField()),
                ('wetlands', models.FloatField()),
                ('waterbodies', models.FloatField()),
                ('year', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.district')),
            ],
        ),
    ]
