# Generated by Django 5.1.3 on 2024-11-29 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_lucpredictiondist'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsagePredictionDist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('rainfall', models.FloatField()),
                ('inflow_states', models.FloatField()),
                ('consumption', models.FloatField()),
                ('irrigation', models.FloatField()),
                ('industry', models.FloatField()),
                ('domestic', models.FloatField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.district')),
            ],
        ),
    ]
