# Generated by Django 5.1.3 on 2024-12-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        
        ('forecast', '0008_landusepast_delete_landuse'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='LandUse',
        # ),
        migrations.AddField(
            model_name='usagepredictiondist',
            name='agriculuture',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usagepredictiondist',
            name='built_up',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usagepredictiondist',
            name='forest',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usagepredictiondist',
            name='wasteland',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usagepredictiondist',
            name='waterbodies',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usagepredictiondist',
            name='wetlands',
            field=models.FloatField(null=True),
        ),
    ]
