# Generated by Django 5.1.3 on 2024-12-12 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0010_delete_landuse_and_more'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='LandUse',
        # ),
        migrations.RemoveField(
            model_name='usagepredictiondist',
            name='inflow_states',
        ),
    ]
