# Generated by Django 5.0.2 on 2024-12-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0012_delete_landuse_remove_usage_inflow_states'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='LandUse',
        # ),
    ]
